services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - HOST=0.0.0.0
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - FALLBACK_LOCALE=${FALLBACK_LOCALE}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - IBKR_HOST=${IBKR_HOST}
      - IBKR_PORT=${IBKR_PORT}
      - IBKR_CLIENT_ID=${IBKR_CLIENT_ID}
      - MARKET_DATA_SOURCE=yahoo
      - NEWS_FETCH_INTERVAL_HOURS=${NEWS_FETCH_INTERVAL_HOURS}
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

volumes:
  frontend: 