# 本地開發配置 - 只運行必要的服務
# 用法: docker-compose -f docker-compose.dev.yml up

version: '3.8'

services:
  # 只運行數據庫，前端和後端在測試服務器上運行
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hellostockbuy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (如果需要緩存)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
