services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - IBKR_HOST=${IBKR_HOST}
      - IBKR_PORT=${IBKR_PORT}
      - IBKR_USER=${IBKR_USER}
      - IBKR_PASSWORD=${IBKR_PASSWORD}
      - MARKET_DATA_SOURCE=yahoo
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  frontend: 