"""add_stock_data_tables

Revision ID: 39d0d3074478
Revises: 74943f09d72e
Create Date: 2025-07-05 09:54:59.189567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d0d3074478'
down_revision: Union[str, None] = '74943f09d72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_date_type', 'fundamental_data', ['symbol', 'date', 'data_type'], unique=False)
    op.create_index(op.f('ix_fundamental_data_date'), 'fundamental_data', ['date'], unique=False)
    op.create_index(op.f('ix_fundamental_data_id'), 'fundamental_data', ['id'], unique=False)
    op.create_index(op.f('ix_fundamental_data_symbol'), 'fundamental_data', ['symbol'], unique=False)
    op.create_table('market_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sentiment_type', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_date_sentiment', 'market_sentiment', ['symbol', 'date', 'sentiment_type'], unique=False)
    op.create_index(op.f('ix_market_sentiment_date'), 'market_sentiment', ['date'], unique=False)
    op.create_index(op.f('ix_market_sentiment_id'), 'market_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_market_sentiment_symbol'), 'market_sentiment', ['symbol'], unique=False)
    op.create_table('stock_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.Column('split_coefficient', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_date', 'stock_daily', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_stock_daily_date'), 'stock_daily', ['date'], unique=False)
    op.create_index(op.f('ix_stock_daily_id'), 'stock_daily', ['id'], unique=False)
    op.create_index(op.f('ix_stock_daily_symbol'), 'stock_daily', ['symbol'], unique=False)
    op.create_table('stock_intraday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_timestamp', 'stock_intraday', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_stock_intraday_id'), 'stock_intraday', ['id'], unique=False)
    op.create_index(op.f('ix_stock_intraday_symbol'), 'stock_intraday', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_intraday_timestamp'), 'stock_intraday', ['timestamp'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('indicator_type', sa.String(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('additional_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_date_indicator', 'technical_indicators', ['symbol', 'date', 'indicator_type'], unique=False)
    op.create_index(op.f('ix_technical_indicators_date'), 'technical_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_symbol'), 'technical_indicators', ['symbol'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('indicators_used', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_date_signal', 'trading_signals', ['symbol', 'date', 'signal_type'], unique=False)
    op.create_index(op.f('ix_trading_signals_date'), 'trading_signals', ['date'], unique=False)
    op.create_index(op.f('ix_trading_signals_id'), 'trading_signals', ['id'], unique=False)
    op.create_index(op.f('ix_trading_signals_symbol'), 'trading_signals', ['symbol'], unique=False)
    op.drop_index('ix_news_published_at', table_name='news')
    op.drop_index('ix_news_source', table_name='news')
    op.add_column('target_symbols', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('target_symbols', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_symbols', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('target_symbols', 'created_at')
    op.create_index('ix_news_source', 'news', ['source'], unique=False)
    op.create_index('ix_news_published_at', 'news', ['published_at'], unique=False)
    op.drop_index(op.f('ix_trading_signals_symbol'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_date'), table_name='trading_signals')
    op.drop_index('idx_symbol_date_signal', table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_technical_indicators_symbol'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_date'), table_name='technical_indicators')
    op.drop_index('idx_symbol_date_indicator', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_stock_intraday_timestamp'), table_name='stock_intraday')
    op.drop_index(op.f('ix_stock_intraday_symbol'), table_name='stock_intraday')
    op.drop_index(op.f('ix_stock_intraday_id'), table_name='stock_intraday')
    op.drop_index('idx_symbol_timestamp', table_name='stock_intraday')
    op.drop_table('stock_intraday')
    op.drop_index(op.f('ix_stock_daily_symbol'), table_name='stock_daily')
    op.drop_index(op.f('ix_stock_daily_id'), table_name='stock_daily')
    op.drop_index(op.f('ix_stock_daily_date'), table_name='stock_daily')
    op.drop_index('idx_symbol_date', table_name='stock_daily')
    op.drop_table('stock_daily')
    op.drop_index(op.f('ix_market_sentiment_symbol'), table_name='market_sentiment')
    op.drop_index(op.f('ix_market_sentiment_id'), table_name='market_sentiment')
    op.drop_index(op.f('ix_market_sentiment_date'), table_name='market_sentiment')
    op.drop_index('idx_symbol_date_sentiment', table_name='market_sentiment')
    op.drop_table('market_sentiment')
    op.drop_index(op.f('ix_fundamental_data_symbol'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_id'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_date'), table_name='fundamental_data')
    op.drop_index('idx_symbol_date_type', table_name='fundamental_data')
    op.drop_table('fundamental_data')
    # ### end Alembic commands ###
