"""add_sentiment_analysis_fields

Revision ID: 74943f09d72e
Revises: e6d4dd45eed0
Create Date: 2025-07-05 00:58:25.410361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74943f09d72e'
down_revision: Union[str, None] = 'e6d4dd45eed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('sentiment_label', sa.String(), nullable=True))
    op.add_column('news', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('news', sa.Column('analysis_method', sa.String(), nullable=True))
    op.add_column('news', sa.Column('textblob_score', sa.Float(), nullable=True))
    op.add_column('news', sa.Column('openai_score', sa.Float(), nullable=True))
    op.drop_constraint('target_symbols_symbol_key', 'target_symbols', type_='unique')
    op.create_index(op.f('ix_target_symbols_id'), 'target_symbols', ['id'], unique=False)
    op.create_index(op.f('ix_target_symbols_symbol'), 'target_symbols', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_symbols_symbol'), table_name='target_symbols')
    op.drop_index(op.f('ix_target_symbols_id'), table_name='target_symbols')
    op.create_unique_constraint('target_symbols_symbol_key', 'target_symbols', ['symbol'])
    op.drop_column('news', 'openai_score')
    op.drop_column('news', 'textblob_score')
    op.drop_column('news', 'analysis_method')
    op.drop_column('news', 'confidence')
    op.drop_column('news', 'sentiment_label')
    # ### end Alembic commands ###
